#!/bin/sh

### BEGIN INIT INFO
# Provides:          mopidy-login
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Restart Mopidy music server as soon as internet connection is available
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Restart Mopidy music server once internet is available"
NAME=mopidy-login
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

echo "mopidy-login"

exit 0
